### PR TITLE
Fix some RDoc formatting and content issues

### PR DESCRIPTION
**Pull request by pond**
* Use of "+" for monospaced text is limited and didn't work in one case - wrapped in <tt>...</tt> instead
* While using my own documents as a reference I noticed an issue where example text was being partially parsed as part of a following code sample due to indentation; fixed
* Noticed no information on simple value types in Hashes, so added a "limitations" section to explain this
* Drive-by fixes to #type and #resource documentation reference to "Hoodoo::Data::Types" (RDoc now auto-links it) and modernised the Hash resource to include both Symbol and Class examples
* Fixed `middleware.rb` ye olde file header reference to `service_middleware.rb`

### CODE REVIEW

**Comment by pjscopeland** [comment]
:+1:

**Comment by pond** [comment]
Closing and re-opening to work around issue where GitHub is waiting for Travis to report status on a build it will never run due to intentional use of `[ci skip]`  in a comment-only commit.

**Comment by mbdietrich** [comment]
👍

**Comment by pond** [comment]
So much for [this](http://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit) - didn't work. Bugs, bugs, bugs everywhere... Trying other approaches short of pushing a pointless commit.

**Pull request merged**
